Repository LikeLion13th-EarthArcade/ArtieBE, pull requests merged in 2025-08, with the labels that each got.

#7 Feat/#2 image 도메인 설계 및 전시 crd api에 image 적용 기능
  build.gradle
  src/main/java/com/project/team5backend/Team5BackEndApplication.java
  src/main/java/com/project/team5backend/domain/image/controller/ImageController.java
  src/main/java/com/project/team5backend/domain/image/converter/ImageConverter.java
  src/main/java/com/project/team5backend/domain/image/dto/internel/ImageInternelDTO.java
  src/main/java/com/project/team5backend/domain/image/dto/request/ImageReqDTO.java
  src/main/java/com/project/team5backend/domain/image/dto/response/ImageResDTO.java
  src/main/java/com/project/team5backend/domain/image/entity/ExhibitionImage.java
  src/main/java/com/project/team5backend/domain/image/entity/ExhibitionReviewImage.java
  src/main/java/com/project/team5backend/domain/image/entity/Image.java
  src/main/java/com/project/team5backend/domain/image/exception/ImageErrorCode.java
  src/main/java/com/project/team5backend/domain/image/exception/ImageException.java
  src/main/java/com/project/team5backend/domain/image/repository/ExhibitionImageRepository.java
  src/main/java/com/project/team5backend/domain/image/repository/ExhibitionReviewImageRepository.java
  src/main/java/com/project/team5backend/domain/image/service/RedisImageTracker.java
  src/main/java/com/project/team5backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/project/team5backend/domain/image/service/command/ImageCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/image/service/scheduler/ImageScheduler.java
  src/main/java/com/project/team5backend/global/config/RedisConfig.java
  src/main/java/com/project/team5backend/global/config/S3Config.java
Labels: ✨feature

#14 Feat/#7 전시리뷰 crd api 구현
  build.gradle
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/converter/ExhibitionConverter.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/dto/response/ExhibitionResDTO.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/entity/Exhibition.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/exception/ExhibitionErrorCode.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/service/command/ExhibitionCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/exhibition/review/controller/ExhibitionReviewController.java
  src/main/java/com/project/team5backend/domain/exhibition/review/converter/ExhibitionReviewConverter.java
  src/main/java/com/project/team5backend/domain/exhibition/review/dto/request/ExhibitionReviewReqDTO.java
  src/main/java/com/project/team5backend/domain/exhibition/review/dto/response/ExhibitionReviewResDTO.java
  src/main/java/com/project/team5backend/domain/exhibition/review/entity/ExhibitionReview.java
  src/main/java/com/project/team5backend/domain/exhibition/review/exception/ExhibitionReviewErrorCode.java
  src/main/java/com/project/team5backend/domain/exhibition/review/exception/ExhibitionReviewException.java
  src/main/java/com/project/team5backend/domain/exhibition/review/repository/ExhibitionReviewRepository.java
  src/main/java/com/project/team5backend/domain/exhibition/review/service/command/ExhibitionReviewCommandService.java
  src/main/java/com/project/team5backend/domain/exhibition/review/service/command/ExhibitionReviewCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/exhibition/review/service/query/ExhibitionReviewQueryService.java
  src/main/java/com/project/team5backend/domain/exhibition/review/service/query/ExhibitionReviewQueryServiceImpl.java
  src/main/java/com/project/team5backend/domain/image/converter/ImageConverter.java
  src/main/java/com/project/team5backend/domain/image/dto/request/ImageReqDTO.java
  src/main/java/com/project/team5backend/domain/image/dto/response/ImageResDTO.java
  src/main/java/com/project/team5backend/domain/image/entity/ExhibitionReviewImage.java
  src/main/java/com/project/team5backend/domain/image/repository/ExhibitionReviewImageRepository.java
  src/main/java/com/project/team5backend/domain/user/repository/UserRepository.java
Labels: ✨feature

#11 Feat/#3 회원가입 로그인 및 회원 관련 기능 구현
  build.gradle
  src/main/java/com/project/team5backend/Team4BackEndApplication.java
  src/main/java/com/project/team5backend/domain/auth/controller/AuthController.java
  src/main/java/com/project/team5backend/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/project/team5backend/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/user/controller/UserController.java
  src/main/java/com/project/team5backend/domain/user/converter/UserConverter.java
  src/main/java/com/project/team5backend/domain/user/dto/request/UserRequest.java
  src/main/java/com/project/team5backend/domain/user/dto/response/UserResponse.java
  src/main/java/com/project/team5backend/domain/user/entity/User.java
  src/main/java/com/project/team5backend/domain/user/repository/UserRepository.java
  src/main/java/com/project/team5backend/domain/user/service/command/UserCommandService.java
  src/main/java/com/project/team5backend/domain/user/service/command/UserCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/user/service/query/UserQueryService.java
  src/main/java/com/project/team5backend/domain/user/service/query/UserQueryServiceImpl.java
  src/main/java/com/project/team5backend/global/BaseEntity.java
  src/main/java/com/project/team5backend/global/apiPayload/CustomResponse.java
  src/main/java/com/project/team5backend/global/apiPayload/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/project/team5backend/global/config/RedisConfig.java
  src/main/java/com/project/team5backend/global/config/SecurityConfig.java
  src/main/java/com/project/team5backend/global/config/SessionConfig.java
  src/main/java/com/project/team5backend/global/config/SwaggerConfig.java
  src/main/java/com/project/team5backend/global/util/CookieUtil.java
Labels: ✨feature

#17 Feat/#8 주소 입력 외부 api 전시 생성에 적용 기능 구현 나머지 전시 관련 기능
  .gitignore
  build.gradle
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/controller/ExhibitionController.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/converter/ExhibitionConverter.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/dto/request/ExhibitionReqDTO.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/dto/response/ExhibitionResDTO.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/entity/Exhibition.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/entity/ExhibitionLike.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/entity/enums/Mood.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/exception/ExhibitionErrorCode.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/repository/ExhibitionRepository.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/repository/ExhibitionRepositoryCustom.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/repository/ExhibitionRepositoryImpl.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/repository/ExhibitionSort.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/service/command/ExhibitionCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/service/query/ExhibitionQueryService.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/service/query/ExhibitionQueryServiceImpl.java
  src/main/java/com/project/team5backend/domain/exhibition/review/controller/ExhibitionReviewController.java
  src/main/java/com/project/team5backend/domain/exhibition/review/converter/ExhibitionReviewConverter.java
  src/main/java/com/project/team5backend/domain/exhibition/review/entity/ExhibitionReview.java
  src/main/java/com/project/team5backend/domain/exhibition/review/repository/ExhibitionReviewRepository.java
  src/main/java/com/project/team5backend/domain/exhibition/review/service/command/ExhibitionReviewCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/exhibition/review/service/query/ExhibitionReviewQueryServiceImpl.java
  src/main/java/com/project/team5backend/domain/image/entity/ExhibitionImage.java
  src/main/java/com/project/team5backend/domain/image/entity/ExhibitionReviewImage.java
  src/main/java/com/project/team5backend/global/address/client/KakaoLocalClient.java
  src/main/java/com/project/team5backend/global/address/converter/AddressConverter.java
  src/main/java/com/project/team5backend/global/address/dto/request/AddressReqDTO.java
  src/main/java/com/project/team5backend/global/address/dto/response/AddressResDTO.java
  src/main/java/com/project/team5backend/global/address/exception/AddressErrorCode.java
  src/main/java/com/project/team5backend/global/address/exception/AddressException.java
  src/main/java/com/project/team5backend/global/address/service/AddressService.java
  src/main/java/com/project/team5backend/global/config/QueryDslConfig.java
  src/main/java/com/project/team5backend/global/config/WebClientConfig.java
  src/main/java/com/project/team5backend/global/entity/BaseOnlyCreateTimeEntity.java
  src/main/java/com/project/team5backend/global/entity/BaseTimeEntity.java
  src/main/java/com/project/team5backend/global/entity/embedded/Address.java
Labels: ✨feature

#24 ✨feat/#14 주소 좌표 변환 기능 적용
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/converter/ExhibitionConverter.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/dto/response/ExhibitionResDTO.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/service/command/ExhibitionCommandServiceImpl.java
  src/main/java/com/project/team5backend/global/address/client/KakaoLocalClient.java
  src/main/java/com/project/team5backend/global/address/converter/AddressConverter.java
  src/main/java/com/project/team5backend/global/address/exception/AddressErrorCode.java
  src/main/java/com/project/team5backend/global/address/service/AddressService.java
  src/main/java/com/project/team5backend/global/config/KakaoRestClientConfig.java
  src/main/java/com/project/team5backend/global/config/WebClientConfig.java
  src/main/java/com/project/team5backend/global/entity/embedded/Address.java
Labels: ✨feature

#34 ♻️ refactor/#2: 인증 인가 로직 적용
  build.gradle
  src/main/java/com/project/team5backend/domain/auth/controller/AuthController.java
  src/main/java/com/project/team5backend/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/project/team5backend/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/user/controller/UserController.java
  src/main/java/com/project/team5backend/domain/user/converter/UserConverter.java
  src/main/java/com/project/team5backend/domain/user/dto/request/UserRequest.java
  src/main/java/com/project/team5backend/domain/user/dto/response/UserResponse.java
  src/main/java/com/project/team5backend/domain/user/entity/Role.java
  src/main/java/com/project/team5backend/domain/user/entity/User.java
  src/main/java/com/project/team5backend/domain/user/repository/UserRepository.java
  src/main/java/com/project/team5backend/domain/user/service/command/UserCommandService.java
  src/main/java/com/project/team5backend/domain/user/service/command/UserCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/user/service/query/UserQueryService.java
  src/main/java/com/project/team5backend/domain/user/service/query/UserQueryServiceImpl.java
  src/main/java/com/project/team5backend/global/BaseEntity.java
  src/main/java/com/project/team5backend/global/apiPayload/CustomResponse.java
  src/main/java/com/project/team5backend/global/apiPayload/CustomUserDetails.java
  src/main/java/com/project/team5backend/global/apiPayload/CustomUserDetailsService.java
  src/main/java/com/project/team5backend/global/apiPayload/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/project/team5backend/global/config/RedisConfig.java
  src/main/java/com/project/team5backend/global/config/SecurityConfig.java
  src/main/java/com/project/team5backend/global/config/SwaggerConfig.java
Labels: ✨feature

#82 Refactor/#81 마이페이지 response 데이터 오류 수정
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/repository/ExhibitionLikeRepository.java
  src/main/java/com/project/team5backend/domain/exhibition/review/repository/ExhibitionReviewRepository.java
  src/main/java/com/project/team5backend/domain/space/entity/Space.java
  src/main/java/com/project/team5backend/domain/space/reservation/converter/ReservationConverter.java
  src/main/java/com/project/team5backend/domain/space/reservation/dto/response/ReservationResponse.java
  src/main/java/com/project/team5backend/domain/space/reservation/entity/Reservation.java
  src/main/java/com/project/team5backend/domain/space/reservation/service/command/ReservationCommandService.java
  src/main/java/com/project/team5backend/domain/space/reservation/service/command/ReservationCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/space/review/entity/Review.java
  src/main/java/com/project/team5backend/domain/space/review/repository/ReviewRepository.java
  src/main/java/com/project/team5backend/domain/space/review/service/command/ReviewCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/space/space/controller/SpaceController.java
  src/main/java/com/project/team5backend/domain/space/space/converter/SpaceConverter.java
  src/main/java/com/project/team5backend/domain/space/space/dto/response/SpaceResponse.java
  src/main/java/com/project/team5backend/domain/space/space/entity/Space.java
  src/main/java/com/project/team5backend/domain/space/space/entity/SpaceLike.java
  src/main/java/com/project/team5backend/domain/space/space/repository/SpaceLikeRepository.java
  src/main/java/com/project/team5backend/domain/space/space/service/command/SpaceCommandService.java
  src/main/java/com/project/team5backend/domain/space/space/service/command/SpaceCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/user/me/controller/UserMeController.java
  src/main/java/com/project/team5backend/domain/user/me/converter/UserMeConverter.java
  src/main/java/com/project/team5backend/domain/user/me/dto/response/UserMeResponse.java
  src/main/java/com/project/team5backend/domain/user/me/entity/Activity.java
  src/main/java/com/project/team5backend/domain/user/me/service/query/UserMeQueryServiceImpl.java
Labels: ♻️refactor

#89 Refactor/#88 전시공간 entitiy 수정
  src/main/java/com/project/team5backend/domain/space/space/controller/SpaceController.java
  src/main/java/com/project/team5backend/domain/space/space/converter/SpaceConverter.java
  src/main/java/com/project/team5backend/domain/space/space/dto/request/SpaceRequest.java
  src/main/java/com/project/team5backend/domain/space/space/entity/Space.java
  src/main/java/com/project/team5backend/domain/space/space/entity/SpaceMood.java
  src/main/java/com/project/team5backend/domain/space/space/entity/SpaceSize.java
  src/main/java/com/project/team5backend/domain/space/space/entity/SpaceType.java
  src/main/java/com/project/team5backend/domain/space/space/service/command/SpaceCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/space/space/service/query/SpaceQueryServiceImpl.java
Labels: ♻️refactor

#91 ♻️refactor : 전시공간리뷰- 이미지 등록 formdata 적용
  src/main/java/com/project/team5backend/domain/space/review/controller/ReviewController.java
  src/main/java/com/project/team5backend/domain/space/review/converter/ReviewConverter.java
  src/main/java/com/project/team5backend/domain/space/review/dto/request/ReviewRequest.java
  src/main/java/com/project/team5backend/domain/space/review/service/command/ReviewCommandService.java
  src/main/java/com/project/team5backend/domain/space/review/service/command/ReviewCommandServiceImpl.java
Labels: ♻️refactor

#96 ♻️refactor/#7: 전시 상세 조회 dto 수정
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/converter/ExhibitionConverter.java
Labels: ♻️refactor

#101 ♻️ refactor/#6:불필요한 코드 정리
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/controller/ExhibitionController.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/converter/ExhibitionConverter.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/dto/response/ExhibitionResDTO.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/repository/ExhibitionRepository.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/service/command/ExhibitionCommandService.java
  src/main/java/com/project/team5backend/domain/exhibition/exhibition/service/command/ExhibitionCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/exhibition/review/service/command/ExhibitionReviewCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/image/controller/ImageController.java
  src/main/java/com/project/team5backend/domain/image/converter/ImageConverter.java
  src/main/java/com/project/team5backend/domain/image/dto/internel/ImageInternelDTO.java
  src/main/java/com/project/team5backend/domain/image/dto/request/ImageReqDTO.java
  src/main/java/com/project/team5backend/domain/image/dto/response/ImageResDTO.java
  src/main/java/com/project/team5backend/domain/image/exception/ImageErrorCode.java
  src/main/java/com/project/team5backend/domain/image/service/RedisImageTracker.java
  src/main/java/com/project/team5backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/project/team5backend/domain/image/service/command/ImageCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/image/service/scheduler/ImageScheduler.java
  src/main/java/com/project/team5backend/domain/space/review/service/command/ReviewCommandServiceImpl.java
  src/main/java/com/project/team5backend/domain/space/space/service/command/SpaceCommandServiceImpl.java
Labels: ♻️refactor

#107 💚cicd/#1: 배포 서버 csrf 보안 검증 활성화 secure 활성화 및 프론트 배포 url CORS 추가
  src/main/java/com/project/team5backend/global/config/SecurityConfig.java
Labels: 💚ci/cd
